#!/usr/bin/env python
import datetime
import requests
import xmltodict
from collections import OrderedDict
from dateutil import parser
from json import dumps
from os import path
from unicodedata import normalize
from app import app

def get_episodes(podcasts):
    episodes = []

    for podcast in podcasts:
        r = requests.get(podcast)
        d = xmltodict.parse(r.text)
        
        _episodes = []
        author = d['rss']['channel']['title']

        for ep in d['rss']['channel']['item']:
            try:
                _episodes.append({
                    'author': author,
                    'pubDate': ep['pubDate'],
                    'date': parser.parse(ep['pubDate']).strftime('%-m/%-d/%Y'),
                    'title': ep['title'],
                    'time': ep['itunes:duration'],
                    'desc': normalize('NFKD', ep['description']),
                    'link': ep['link'],
                    'mp3': ep['enclosure']['@url'].replace('http://', 'https://')
                })
            except:
                pass
    
        episodes += _episodes
   
    episodes = sorted(episodes, key=lambda k: parser.parse(k['pubDate']), reverse=True)
    
    return episodes


if __name__ == "__main__":
    eps = get_episodes(app.config['PODCASTS_CSV'].split(','))
    if eps:
        with open(path.join(app.root_path, 'persist/episodes'), 'w+') as f:
            f.write(dumps(eps))
 
