#!/usr/bin/env python
import datetime
import re
import requests
import xmltodict
from collections import OrderedDict
from dateutil import parser
from json import dumps
from os import path
from app import app

def get_episodes(podcasts):
    episodes = []

    for podcast in podcasts:
        r = requests.get(podcast)
        d = xmltodict.parse(r.text)
        
        _episodes = d['rss']['channel']['item']
        author = d['rss']['channel']['title']

        for i, ep in enumerate(_episodes):
            try:
                _episodes[i] = {
                    'author': author,
                    'pubDate': ep['pubDate'],
                    'date': parser.parse(ep['pubDate']).strftime('%-m/%-d/%Y'),
                    'title': ep['title'],
                    'time': re.sub(r'\s+', ' ', ep['itunes:duration']),
                    'desc': ep['description'],
                    'link': ep['link'],
                    'mp3': ep['enclosure']['@url'].replace('http://', 'https://')
                }

            except:
                pass
    
        if isinstance(_episodes, list):
            episodes += _episodes
        else:  # New show, single ep
            episodes.append(_episodes)
   
    episodes = sorted(episodes, key=lambda k: parser.parse(k['pubDate']), reverse=True)

    return episodes


if __name__ == "__main__":
    eps = get_episodes(app.config['PODCASTS_CSV'].split(','))
    if eps:
        with open(path.join(app.root_path, 'persist/episodes'), 'w+') as f:
            f.write(dumps(eps))
 
